export * from './base'
export {default as PermissionGroup} from './permission-group'
export {default as PermissionType} from './permission-types'
export {default as Permission} from './permission'
export {default as Role} from './role'
export {default as Admin} from './admin'
export {default as User} from './user'
export {default as UserRole} from './user-role'
export {default as UserPermissionGroup} from './user-permission-group'
export {default as UserPermission} from './user-permission'
export {default as AcademicRecords} from './academic-records'
export {default as Application} from './applications'
export {default as Document} from './documents'
export {default as University} from './universities'
export {default as AdmissionMethod} from './admission_methods'
export {default as Notification} from './notifications'
export {default as Combination} from './combinations'
export {default as Major} from './majors'
export {default as SubjectScore} from './subject_scores'
export {default as UniversityExamScore} from './university_exam_scores'
export {default as DirectAdmission} from './direct_admissions'
export {default as TalentApplication} from './talent_applications'
export {default as InternationalCertificate} from './international_certificates'


